# Generated by Django 4.2.7 on 2024-01-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_delete_post2"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("file_upload", models.FileField(upload_to="intro/image/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Main_Stage_Images",
            },
        ),
    ]
