# Generated by Django 4.2.7 on 2024-01-05 00:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_post2"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post2",
        ),
    ]
