# Generated by Django 4.2.7 on 2024-01-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("single_pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intro_img", models.FileField(blank=True, upload_to="intro/images2")),
                ("title", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Intro_Image-seyun",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name_plural": "Intro_Image"},
        ),
        migrations.AlterField(
            model_name="post",
            name="intro_img",
            field=models.FileField(blank=True, upload_to="intro/images"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
